import type { FlashcardPack } from "./types";

export const flashcardPacks: FlashcardPack[] = [
  // ---------- Tier: Foundation ----------
  {
    level: 'Red',
    type: null,
    pairs: [
      { hebrew: 'שָׁלוֹם', english: 'Hello / Peace' },
      { hebrew: 'תּוֹדָה', english: 'Thank you' },
      { hebrew: 'בְּבַקָּשָׁה', english: 'Please / You\'re welcome' },
      { hebrew: 'כֵּן', english: 'Yes' },
      { hebrew: 'לֹא', english: 'No' },
      { hebrew: 'לְהִתְרָאוֹת', english: 'Goodbye' },
      { hebrew: 'סְלִיחָה', english: 'Sorry / Excuse me' },
      { hebrew: 'שֵׁם', english: 'Name' },
      { hebrew: 'מָה', english: 'What' },
      { hebrew: 'אֵיךְ', english: 'How' },
    ],
  },
  {
    level: 'Orange',
    type: null,
    pairs: [
      { hebrew: 'אֶחָד', english: 'One' },
      { hebrew: 'שְׁתַּיִם', english: 'Two' },
      { hebrew: 'שָׁלוֹשׁ', english: 'Three' },
      { hebrew: 'אַרְבַּע', english: 'Four' },
      { hebrew: 'חָמֵשׁ', english: 'Five' },
      { hebrew: 'שֵׁשׁ', english: 'Six' },
      { hebrew: 'שֶׁבַע', english: 'Seven' },
      { hebrew: 'שְׁמוֹנֶה', english: 'Eight' },
      { hebrew: 'תֵּשַׁע', english: 'Nine' },
      { hebrew: 'עֶשֶׂר', english: 'Ten' },
    ],
  },
  {
    level: 'Pink',
    type: null,
    pairs: [
      { hebrew: 'מִשְׁפָּחָה', english: 'Family' },
      { hebrew: 'אִמָּא', english: 'Mom' },
      { hebrew: 'אַבָּא', english: 'Dad' },
      { hebrew: 'אָח', english: 'Brother' },
      { hebrew: 'אָחוֹת', english: 'Sister' },
      { hebrew: 'סַבָּא', english: 'Grandpa' },
      { hebrew: 'סָבְתָא', english: 'Grandma' },
      { hebrew: 'בֵּן', english: 'Son' },
      { hebrew: 'בַּת', english: 'Daughter' },
      { hebrew: 'יֶלֶד', english: 'Child / Boy' },
    ],
  },
  {
    level: 'Yellow',
    type: null,
    pairs: [
      { hebrew: 'צֶבַע', english: 'Color' },
      { hebrew: 'אָדֹם', english: 'Red' },
      { hebrew: 'כָּחֹל', english: 'Blue' },
      { hebrew: 'יָרֹק', english: 'Green' },
      { hebrew: 'צָהֹב', english: 'Yellow' },
      { hebrew: 'שָׁחֹר', english: 'Black' },
      { hebrew: 'לָבָן', english: 'White' },
      { hebrew: 'גָּדוֹל', english: 'Big' },
      { hebrew: 'קָטָן', english: 'Small' },
      { hebrew: 'יָפֶה', english: 'Beautiful' },
    ],
  },

  // ---------- Tier: Flow ----------
  {
    level: 'LightBlue',
    type: null,
    pairs: [
      { hebrew: 'לָלֶכֶת', english: 'To go' },
      { hebrew: 'לֶאֱכֹל', english: 'To eat' },
      { hebrew: 'לִשְׁתּוֹת', english: 'To drink' },
      { hebrew: 'לִישֹׁן', english: 'To sleep' },
      { hebrew: 'לַעֲבֹד', english: 'To work' },
      { hebrew: 'לִלְמֹד', english: 'To study' },
      { hebrew: 'לִרְצוֹת', english: 'To want' },
      { hebrew: 'לְהִצְטָרֵךְ', english: 'To need' },
      { hebrew: 'לֶאֱהֹב', english: 'To love / like' },
      { hebrew: 'לָדַעַת', english: 'To know' },
    ],
  },
  {
    level: 'Blue',
    type: null,
    pairs: [
      { hebrew: 'הַיּוֹם', english: 'Today' },
      { hebrew: 'מָחָר', english: 'Tomorrow' },
      { hebrew: 'אֶתְמוֹל', english: 'Yesterday' },
      { hebrew: 'שָׁבוּעַ', english: 'Week' },
      { hebrew: 'חֹדֶשׁ', english: 'Month' },
      { hebrew: 'בֹּקֶר', english: 'Morning' },
      { hebrew: 'לַיְלָה', english: 'Night' },
      { hebrew: 'שָׁעָה', english: 'Hour' },
      { hebrew: 'עַכְשָׁו', english: 'Now' },
      { hebrew: 'אַחַר כָּךְ', english: 'Later' },
    ],
  },
  {
    level: 'Lime',
    type: null,
    pairs: [
      { hebrew: 'מִסְעָדָה', english: 'Restaurant' },
      { hebrew: 'תַּפְרִיט', english: 'Menu' },
      { hebrew: 'מַיִם', english: 'Water' },
      { hebrew: 'קָפֶה', english: 'Coffee' },
      { hebrew: 'לֶחֶם', english: 'Bread' },
      { hebrew: 'הַחֶשְׁבּוֹן בְּבַקָּשָׁה', english: 'Check, please' },
      { hebrew: 'טָעִים', english: 'Delicious' },
      { hebrew: 'רָעֵב', english: 'Hungry' },
      { hebrew: 'לְהַזְמִין', english: 'To order' },
      { hebrew: 'חֶשְׁבּוֹן', english: 'Bill' },
    ],
  },
  {
    level: 'Green',
    type: null,
    pairs: [
      { hebrew: 'שְׂמֹאלָה', english: 'Left' },
      { hebrew: 'יָמִינָה', english: 'Right' },
      { hebrew: 'יָשָׁר', english: 'Straight' },
      { hebrew: 'אֵיפֹה', english: 'Where' },
      { hebrew: 'רְחוֹב', english: 'Street' },
      { hebrew: 'אוֹטוֹבּוּס', english: 'Bus' },
      { hebrew: 'רַכֶּבֶת', english: 'Train' },
      { hebrew: 'שְׂדֵה תְּעוּפָה', english: 'Airport' },
      { hebrew: 'כַּרְטִיס', english: 'Ticket' },
      { hebrew: 'מַפָּה', english: 'Map' },
    ],
  },

  // ---------- Tier: Freedom ----------
  // DarkGreen — 4 topic packs
  {
    level: 'DarkGreen',
    type: 1,
    pairs: [
      { hebrew: 'עֲבוֹדָה', english: 'Job / Work' },
      { hebrew: 'פְּגִישָׁה', english: 'Meeting' },
      { hebrew: 'מַשְׂכֹּרֶת', english: 'Salary' },
      { hebrew: 'חוֹזֶה', english: 'Contract' },
      { hebrew: 'עֵסֶק', english: 'Business' },
      { hebrew: 'עוֹבֵד', english: 'Employee' },
      { hebrew: 'מְנַהֵל', english: 'Manager' },
      { hebrew: 'לָקוֹחַ', english: 'Client' },
      { hebrew: 'תַּקְצִיב', english: 'Budget' },
      { hebrew: 'הַשְׁקָעָה', english: 'Investment' },
    ],
  },
  {
    level: 'DarkGreen',
    type: 2,
    pairs: [
      { hebrew: 'בְּרִיאוּת', english: 'Health' },
      { hebrew: 'רוֹפֵא', english: 'Doctor' },
      { hebrew: 'בֵּית חוֹלִים', english: 'Hospital' },
      { hebrew: 'תְּרוּפָה', english: 'Medicine' },
      { hebrew: 'כְּאֵב', english: 'Pain' },
      { hebrew: 'חוֹם', english: 'Fever' },
      { hebrew: 'לֵב', english: 'Heart' },
      { hebrew: 'רֹאשׁ', english: 'Head' },
      { hebrew: 'בֶּטֶן', english: 'Stomach' },
      { hebrew: 'לְהַרְגִּישׁ', english: 'To feel' },
    ],
  },
  {
    level: 'DarkGreen',
    type: 3,
    pairs: [
      { hebrew: 'שָׂמֵחַ', english: 'Happy' },
      { hebrew: 'עָצוּב', english: 'Sad' },
      { hebrew: 'כּוֹעֵס', english: 'Angry' },
      { hebrew: 'מְפֻחָד', english: 'Scared' },
      { hebrew: 'נִרְגָּשׁ', english: 'Excited' },
      { hebrew: 'עָיֵף', english: 'Tired' },
      { hebrew: 'מוּדְאָג', english: 'Worried' },
      { hebrew: 'גֵּאֶה', english: 'Proud' },
      { hebrew: 'מְבֻלְבָּל', english: 'Confused' },
      { hebrew: 'רָגוּעַ', english: 'Calm' },
    ],
  },
  {
    level: 'DarkGreen',
    type: 4,
    pairs: [
      { hebrew: 'מַחְשֵׁב', english: 'Computer' },
      { hebrew: 'טֶלֶפוֹן', english: 'Phone' },
      { hebrew: 'אִינְטֶרְנֶט', english: 'Internet' },
      { hebrew: 'אַפְּלִיקַצְיָה', english: 'Application' },
      { hebrew: 'סִיסְמָה', english: 'Password' },
      { hebrew: 'מָסָךְ', english: 'Screen' },
      { hebrew: 'תָּכְנָה', english: 'Software' },
      { hebrew: 'רֶשֶׁת', english: 'Network' },
      { hebrew: 'קוֹבֶץ', english: 'File' },
      { hebrew: 'לְהוֹרִיד', english: 'To download' },
    ],
  },

  // Turquoise — 4 topic packs
  {
    level: 'Turquoise',
    type: 1,
    pairs: [
      { hebrew: 'חַג', english: 'Holiday' },
      { hebrew: 'פֶּסַח', english: 'Passover' },
      { hebrew: 'רֹאשׁ הַשָּׁנָה', english: 'New Year (Jewish)' },
      { hebrew: 'חֲנֻכָּה', english: 'Hanukkah' },
      { hebrew: 'שַׁבָּת', english: 'Sabbath' },
      { hebrew: 'מָסֹרֶת', english: 'Tradition' },
      { hebrew: 'תַּרְבּוּת', english: 'Culture' },
      { hebrew: 'חֲגִיגָה', english: 'Celebration' },
      { hebrew: 'בֵּית כְּנֶסֶת', english: 'Synagogue' },
      { hebrew: 'נֵר', english: 'Candle' },
    ],
  },
  {
    level: 'Turquoise',
    type: 2,
    pairs: [
      { hebrew: 'טֶבַע', english: 'Nature' },
      { hebrew: 'מֶזֶג אֲוִיר', english: 'Weather' },
      { hebrew: 'שֶׁמֶשׁ', english: 'Sun' },
      { hebrew: 'גֶּשֶׁם', english: 'Rain' },
      { hebrew: 'רוּחַ', english: 'Wind' },
      { hebrew: 'עָנָן', english: 'Cloud' },
      { hebrew: 'הַר', english: 'Mountain' },
      { hebrew: 'יָם', english: 'Sea' },
      { hebrew: 'יַעַר', english: 'Forest' },
      { hebrew: 'פֶּרַח', english: 'Flower' },
    ],
  },
  {
    level: 'Turquoise',
    type: 3,
    pairs: [
      { hebrew: 'סְפּוֹרְט', english: 'Sport' },
      { hebrew: 'כַּדּוּרֶגֶל', english: 'Soccer' },
      { hebrew: 'שְׂחִיָּה', english: 'Swimming' },
      { hebrew: 'רִיצָה', english: 'Running' },
      { hebrew: 'תַּחְבִּיב', english: 'Hobby' },
      { hebrew: 'צִיּוּר', english: 'Painting' },
      { hebrew: 'מוּסִיקָה', english: 'Music' },
      { hebrew: 'קְרִיאָה', english: 'Reading' },
      { hebrew: 'מִשְׂחָק', english: 'Game' },
      { hebrew: 'אִמּוּן', english: 'Training' },
    ],
  },
  {
    level: 'Turquoise',
    type: 4,
    pairs: [
      { hebrew: 'חֲדָשׁוֹת', english: 'News' },
      { hebrew: 'עִתּוֹן', english: 'Newspaper' },
      { hebrew: 'כְּתָבָה', english: 'Article' },
      { hebrew: 'עוֹרֵךְ', english: 'Editor' },
      { hebrew: 'שִׁדּוּר', english: 'Broadcast' },
      { hebrew: 'רֶשֶׁת חֶבְרָתִית', english: 'Social network' },
      { hebrew: 'פִּרְסֹמֶת', english: 'Advertisement' },
      { hebrew: 'רַאֲיוֹן', english: 'Interview' },
      { hebrew: 'עִתּוֹנַאי', english: 'Journalist' },
      { hebrew: 'כּוֹתֶרֶת', english: 'Headline' },
    ],
  },

  // Indigo — 6 topic packs
  {
    level: 'Indigo',
    type: 1,
    pairs: [
      { hebrew: 'חֹק', english: 'Law' },
      { hebrew: 'מֶמְשָׁלָה', english: 'Government' },
      { hebrew: 'שׁוֹפֵט', english: 'Judge' },
      { hebrew: 'בְּחִירוֹת', english: 'Elections' },
      { hebrew: 'אֶזְרָח', english: 'Citizen' },
      { hebrew: 'זְכוּת', english: 'Right' },
      { hebrew: 'חוֹבָה', english: 'Obligation / Duty' },
      { hebrew: 'בֵּית מִשְׁפָּט', english: 'Court' },
      { hebrew: 'חֻקָּה', english: 'Constitution' },
      { hebrew: 'חֵרוּת', english: 'Freedom' },
    ],
  },
  {
    level: 'Indigo',
    type: 2,
    pairs: [
      { hebrew: 'אֱמֶת', english: 'Truth' },
      { hebrew: 'מַשְׁמָעוּת', english: 'Meaning' },
      { hebrew: 'תּוֹדָעָה', english: 'Consciousness' },
      { hebrew: 'מוּסָר', english: 'Ethics / Morality' },
      { hebrew: 'קִיּוּם', english: 'Existence' },
      { hebrew: 'תַּכְלִית', english: 'Purpose' },
      { hebrew: 'סִבָּה', english: 'Cause' },
      { hebrew: 'תּוֹצָאָה', english: 'Result' },
      { hebrew: 'הַכָּרָה', english: 'Awareness / Recognition' },
      { hebrew: 'בְּחִירָה חָפְשִׁית', english: 'Free will' },
    ],
  },
  {
    level: 'Indigo',
    type: 3,
    pairs: [
      { hebrew: 'סִפְרוּת', english: 'Literature' },
      { hebrew: 'סִפּוּר', english: 'Story' },
      { hebrew: 'שִׁיר', english: 'Poem' },
      { hebrew: 'מֶטָפוֹרָה', english: 'Metaphor' },
      { hebrew: 'גִּבּוֹר', english: 'Hero' },
      { hebrew: 'עֲלִילָה', english: 'Plot' },
      { hebrew: 'מְחַבֵּר', english: 'Author' },
      { hebrew: 'פִּתְגָּם', english: 'Proverb' },
      { hebrew: 'פֵּרוּשׁ', english: 'Interpretation' },
      { hebrew: 'הַשְׁרָאָה', english: 'Inspiration' },
    ],
  },
  {
    level: 'Indigo',
    type: 4,
    pairs: [
      { hebrew: 'סַבַּבָּה', english: 'Cool / OK' },
      { hebrew: 'אַחְלָה', english: 'Great / Nice' },
      { hebrew: 'כְּאִלּוּ', english: 'Like / I mean' },
      { hebrew: 'סְתָם', english: 'Just / No reason' },
      { hebrew: 'וָואלָה', english: 'Really? / Wow' },
      { hebrew: 'חֶבְרֶה', english: 'Guys / folks' },
      { hebrew: 'בּוֹא נֵלֵךְ', english: "Let's go" },
      { hebrew: 'אֵיזֶה כֵּיף', english: 'How fun' },
      { hebrew: 'יַאלְלָה', english: "Come on / let's go" },
      { hebrew: 'מְגַנְיָב', english: 'Awesome / cool' },
    ],
  },
  {
    level: 'Indigo',
    type: 5,
    pairs: [
      { hebrew: 'מַדָּע', english: 'Science' },
      { hebrew: 'מֶחְקָר', english: 'Research' },
      { hebrew: 'נִסּוּי', english: 'Experiment' },
      { hebrew: 'תֵּאוֹרְיָה', english: 'Theory' },
      { hebrew: 'הַשְׁעָרָה', english: 'Hypothesis' },
      { hebrew: 'נְתוּנִים', english: 'Data' },
      { hebrew: 'אוּנִיבֶרְסִיטָה', english: 'University' },
      { hebrew: 'תֵּזָה', english: 'Thesis' },
      { hebrew: 'הוֹכָחָה', english: 'Proof' },
      { hebrew: 'תוֹצָאוֹת', english: 'Results' },
    ],
  },
  {
    level: 'Indigo',
    type: 6,
    pairs: [
      { hebrew: 'הִיסְטוֹרְיָה', english: 'History' },
      { hebrew: 'תְּקוּפָה', english: 'Era / Period' },
      { hebrew: 'מִלְחָמָה', english: 'War' },
      { hebrew: 'שָׁלוֹם', english: 'Peace (treaty)' },
      { hebrew: 'אִימְפֶּרְיָה', english: 'Empire' },
      { hebrew: 'מַהְפֵּכָה', english: 'Revolution' },
      { hebrew: 'עַתִּיק', english: 'Ancient' },
      { hebrew: 'תַּגְלִית', english: 'Discovery' },
      { hebrew: 'שֹׁרֶשׁ', english: 'Root / origin' },
      { hebrew: 'מוֹרֶשֶׁת', english: 'Heritage' },
    ],
  },

  // Purple — native-level idioms, single pack
  {
    level: 'Purple',
    type: null,
    pairs: [
      { hebrew: 'אֵין דָּבָר', english: "It's nothing / no worries" },
      { hebrew: 'מַה שֶּׁהָיָה הָיָה', english: "What's done is done" },
      { hebrew: 'כֹּל הַכָּבוֹד', english: 'Well done / respect' },
      { hebrew: 'שֶׁקֶט תַּעֲשִׂיָּתִי', english: 'Radio silence' },
      { hebrew: 'יוֹרֵד גְּשָׁמִים כְּמוֹ מִן הַדְּלִי', english: 'Raining cats and dogs' },
      { hebrew: 'לֹא נוֹרָא', english: 'No big deal' },
      { hebrew: 'עַל הַפָּנִים', english: 'Terrible / awful' },
      { hebrew: 'מֵת עַל זֶה', english: 'Loves it (dying for it)' },
      { hebrew: 'סוֹף הָעוֹלָם שְׂמֹאלָה', english: 'The middle of nowhere' },
      { hebrew: 'חָתוּל בְּשַׂק', english: 'Pig in a poke' },
    ],
  },
];
